### ISSUE TITLE
Translation home page

### ISSUE THREAD

**Issue by mishmanners** [mishmanners/mish-friendly-food#101]
We'd love someone to help us to the translation piece on the website. You'll see that there is currently just all the translations available as a text. We want people to be able to use a text box to translate and get their translation back.

Let us know if you want to help out here.

**Comment by alt-shreya** [comment]
@mishmanners I'd like to give this a shot.

**Comment by mishmanners** [comment]
Yes please go ahead @alt-shreya

**Comment by alt-shreya** [comment]
@mishmanners while trying to setup the website locally, I encountered some vulnerabilities.

Might want to take a look: ```7 vulnerabilities (1 low, 2 moderate, 3 high, 1 critical) ```

The way I worked around this was to run ```npm audit fix```
