### ISSUE TITLE
Logo vectorise

### ISSUE THREAD

**Issue by mishmanners** [mishmanners/mish-friendly-food#24]
If someone could vectorise the logo that'd be epic:
https://github.com/mishmanners/mish-friendly-food/tree/main/Images/Logo

**Comment by mishmanners** [comment]
We actually have an awesome logo here: https://github.com/mishmanners/mish-friendly-food/issues/13#issuecomment-1290057057 thanks to @VaishantMakan ❤️

**Comment by VaishantMakan** [comment]
@mishmanners 
Hey! I think you have mentioned the wrong person here 😊

**Comment by mishmanners** [comment]
Ooops, sorry for that. All done now and this issue should close once we merge the PR 😄
