### ISSUE TITLE
TODO: Add .TakeAction

### ISSUE THREAD

**Issue by mishmanners** [mishmanners/mish-friendly-food#84]
Add Action for autoassign.

Thanks to @blackgirlbytes ❤️

**Comment by mishmanners** [comment]
https://github.com/marketplace/actions/contributor-takes-action
Thanks to @bdougie for building this action!

**Comment by mishmanners** [comment]
.TakeAction

**Comment by mishmanners** [comment]
.take

**Comment by mishmanners** [comment]
.take

**Comment by mishmanners** [comment]
I want to .take this issue

**Comment by mishmanners** [comment]
.take

**Comment by mishmanners** [comment]
.take

**Comment by mishmanners** [comment]
I want to .take this issue

**Comment by mishmanners** [comment]
.take

**Comment by mishmanners** [comment]
I want to .take this issues please.

**Comment by mishmanners** [comment]
I want to .take this issue please.

**Comment by mishmanners** [comment]
I want to .take this issue please.

**Comment by mishmanners** [comment]
.take

**Comment by mishmanners** [comment]
I want to .take this issue

**Comment by mishmanners** [comment]
Can I .take this now?

**Comment by mishmanners** [comment]
Now can we .take action

**Comment by Damovisa** [comment]
Maybe I can .take it?

**Comment by Damovisa** [comment]
Try to .take it again

**Comment by mishmanners** [comment]
.take

**Comment by Damovisa** [comment]
.take

**Comment by mishmanners** [comment]
yay it works!
